from dataclasses import dataclass
from typing import Any, Protocol


@dataclass(frozen=True)
class ReportRecord:
    barcode: str
    html: bytes
    archived: bool
    query_slot: str
    updated_at: str


@dataclass(frozen=True)
class EntityRecord:
    key: str
    payload: dict[str, Any]
    deleted: bool
    updated_at: str


class StorageBackend(Protocol):
    def list_reports(self, archived: bool = False) -> list[str]: ...
    def get_report(self, barcode: str) -> ReportRecord | None: ...
    def put_report(self, record: ReportRecord) -> None: ...
    def delete_report(self, barcode: str, actor: str = "system") -> bool: ...
    def load_entities(self, kind: str, include_deleted: bool = False) -> list[EntityRecord]: ...
    def get_entity(self, kind: str, key: str) -> EntityRecord | None: ...
    def put_entity(self, kind: str, key: str, payload: dict[str, Any], actor: str = "system") -> None: ...
    def delete_entity(self, kind: str, key: str, actor: str = "system") -> bool: ...
    def append_log(self, category: str, level: str, message: str, context: dict[str, Any] | None = None) -> str: ...
    def list_logs(self, category: str, limit: int = 500) -> list[dict[str, Any]]: ...
